# Generated by Django 4.1.7 on 2023-04-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0003_alter_productseries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
