# Generated by Django 4.2 on 2023-05-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
