# Generated by Django 4.1.7 on 2023-04-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_cartitem_purchaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='purchaser',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
