# Generated by Django 4.1.7 on 2023-04-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchasedProduct',
        ),
    ]
