# Generated by Django 4.1.7 on 2023-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
