# Generated by Django 4.1.7 on 2023-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_alter_article_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='article_images'),
            preserve_default=False,
        ),
    ]
